import React, { useState, useEffect } from 'react';
import Navbar from './components/Navbar';
import DashboardHome from './components/DashboardHome';
import ActivityLedger from './components/ActivityLedger';
import ManualEntry from './components/ManualEntry';
import AssetDetail from './components/AssetDetail';
import { Calendar, RefreshCw } from 'lucide-react';
import './App.css';

export default function App() {
  const [activeTab, setActiveTab] = useState('dashboard');
  const [portfolioData, setPortfolioData] = useState(null);
  const [selectedAsset, setSelectedAsset] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Manual Assets local storage state
  const [manualAssets, setManualAssets] = useState(() => {
    const saved = localStorage.getItem('matad_manual_assets');
    return saved ? JSON.parse(saved) : [
      { id: 'm1', symbol: 'BTC-USD', name: 'Bitcoin', qty: 0.5, avgPrice: 42000, currentPrice: 68500, type: 'Crypto' },
      { id: 'm2', symbol: 'ETH-USD', name: 'Ethereum', qty: 4.0, avgPrice: 2400, currentPrice: 3500, type: 'Crypto' },
      { id: 'm3', symbol: 'CASH-USD', name: 'Savings Cash', qty: 15000, avgPrice: 1.0, currentPrice: 1.0, type: 'Cash' }
    ];
  });

  const [manualTransactions, setManualTransactions] = useState(() => {
    const saved = localStorage.getItem('matad_manual_tx');
    return saved ? JSON.parse(saved) : [
      { id: 'mt1', date: '2026-02-15', type: 'BUY', symbol: 'BTC-USD', qty: 0.5, price: 42000, amount: 21000, owner: 'Manual', broker: 'Manual Tracking' },
      { id: 'mt2', date: '2026-03-10', type: 'BUY', symbol: 'ETH-USD', qty: 4.0, price: 2400, amount: 9600, owner: 'Manual', broker: 'Manual Tracking' },
      { id: 'mt3', date: '2026-01-01', type: 'BUY', symbol: 'CASH-USD', qty: 15000, price: 1.0, amount: 15000, owner: 'Manual', broker: 'Manual Tracking' }
    ];
  });

  // Sync manual assets and transactions to LocalStorage
  useEffect(() => {
    localStorage.setItem('matad_manual_assets', JSON.stringify(manualAssets));
  }, [manualAssets]);

  useEffect(() => {
    localStorage.setItem('matad_manual_tx', JSON.stringify(manualTransactions));
  }, [manualTransactions]);

  // Load compiled portfolio data
  const loadData = async () => {
    setLoading(true);
    setError(null);
    try {
      // Fetch the compiled data file generated by our build script
      const res = await fetch('./data/portfolio.json');
      if (!res.ok) {
        throw new Error('Could not retrieve compiled portfolio JSON.');
      }
      const data = await res.json();
      setPortfolioData(data);
    } catch (err) {
      console.warn('Failed to load portfolio.json, retrying or checking fallback...', err);
      setError('Failed to load compiled portfolio file. Please run the build script `node scripts/build-data.js` first.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, []);

  // Determine connection status
  const isMock = portfolioData?.summary?.lastUpdated ? false : true;
  const lastUpdatedString = portfolioData?.summary?.lastUpdated
    ? new Date(portfolioData.summary.lastUpdated).toLocaleString()
    : 'No active connection';

  return (
    <div className="app-container">
      
      {/* Sidebar Navigation */}
      <Navbar activeTab={activeTab} setActiveTab={setActiveTab} />

      {/* Main Container */}
      <main className="app-content">
        
        {/* Top Header */}
        <header className="content-header">
          <div className="header-title-area">
            <h1>MATAD Holdings</h1>
            <p>Aggregated family office dashboard & asset visualizer</p>
          </div>

          <div className="header-actions">
            {/* Last updated info */}
            <div className="status-badge">
              <Calendar size={14} />
              <span>Updated: {lastUpdatedString}</span>
            </div>

            {/* Connection Mode */}
            <div className="status-badge">
              {loading ? (
                <>
                  <span className="status-dot loading"></span>
                  <span>Loading Data...</span>
                </>
              ) : error ? (
                <>
                  <span className="status-dot" style={{ backgroundColor: 'hsl(var(--danger))', boxShadow: '0 0 10px hsl(var(--danger))' }}></span>
                  <span>Connection Error</span>
                </>
              ) : (
                <>
                  <span className="status-dot"></span>
                  <span>{isMock ? 'Simulated Portfolio' : 'API Aggregation Connected'}</span>
                </>
              )}
            </div>

            {/* Manual Reload */}
            <button 
              onClick={loadData} 
              className="glass-button secondary" 
              style={{ padding: '8px 12px', minWidth: 'auto' }}
              title="Refresh local data"
              disabled={loading}
            >
              <RefreshCw size={14} className={loading ? 'loading' : ''} style={{ animation: loading ? 'pulse 1s infinite' : 'none' }} />
            </button>
          </div>
        </header>

        {/* Dynamic Inner Tab View */}
        {loading ? (
          <div style={{ display: 'flex', height: '50vh', alignItems: 'center', justifyContent: 'center', flexDirection: 'column', gap: '15px' }}>
            <div className="status-dot loading" style={{ width: '12px', height: '12px' }}></div>
            <p style={{ color: 'hsl(var(--text-secondary))' }}>Loading MATAD data tables...</p>
          </div>
        ) : error ? (
          <div className="glass-panel" style={{ padding: '40px', textAlign: 'center', maxWidth: '600px', margin: '40px auto' }}>
            <h3 style={{ color: 'hsl(var(--danger))', marginBottom: '15px' }}>Data Initialization Error</h3>
            <p style={{ color: 'hsl(var(--text-secondary))', marginBottom: '25px' }}>{error}</p>
            <button onClick={loadData} className="glass-button">Retry Connection</button>
          </div>
        ) : (
          <>
            {activeTab === 'dashboard' && (
              <DashboardHome 
                data={portfolioData} 
                onSelectAsset={(asset) => setSelectedAsset(asset)}
                manualAssets={manualAssets}
              />
            )}

            {activeTab === 'ledger' && (
              <ActivityLedger 
                data={portfolioData} 
                manualTransactions={manualTransactions} 
              />
            )}

            {activeTab === 'manual' && (
              <ManualEntry 
                manualAssets={manualAssets} 
                setManualAssets={setManualAssets} 
                manualTransactions={manualTransactions} 
                setManualTransactions={setManualTransactions} 
              />
            )}
          </>
        )}
      </main>

      {/* Asset Detail Overlay Modal */}
      {selectedAsset && (
        <AssetDetail 
          asset={selectedAsset} 
          data={portfolioData} 
          manualTransactions={manualTransactions}
          onClose={() => setSelectedAsset(null)}
        />
      )}
      
    </div>
  );
}
